version: '3.8'

services:

  db:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    env_file:
      - ./nodejs-api/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  front:
    build: ./angular-qrcode
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always

  api:
    build: ./nodejs-api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

volumes:
  pg_data: