version: '3.8'

services:

  db:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    env_file:
      - ./nodejs-api/.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  angular-qrcode:
    build: ./angular-qrcode
    ports:
      - "80:80"
    depends_on:
      - nodejs-api
    restart: always

  nodejs-api:
    build: ./nodejs-api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./nodejs-api/.env
    ports:
      - "5050:80"

volumes:
  pg_data: